name: Get TV Source
on:
  schedule:
    # 每天的 19:00 UTC / CST 4:00 自动触发同步
    - cron: '0 19 * * *'
  workflow_dispatch:
    # 手动触发同步

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出当前仓库
    - name: Checkout this repository
      uses: actions/checkout@v4

    # Step 2: 克隆目标仓库
    - name: Clone target repository
      run: |
        git clone --depth 1 https://github.com/Ftindy/IPTV-URL.git target-repo
    
    # Step 3: 复制需要同步的文件
    - name: Copy files
      run: |
        cp -R target-repo/* tvsrc
        rm -rf target-repo
        curl https://raw.githubusercontent.com/wwb521/live/refs/heads/main/tv.m3u -o tvsrc/live.m3u
    
    # Step 4: 提交和推送更改
    - name: Commit and push changes
      run: |
        echo "Starting script"
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        if git diff --cached --quiet; then
          echo "No changes detected"
          exit 0
        else
          echo "Changes detected"
          git commit -m "update TV source" 
          git push
        fi
        

      env:
        # 提交需要 GitHub Token 来验证推送操作
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
