name: Sync files from another repository

on:
  schedule:
    # 每天的 19:00 UTC / CST 4:00 自动触发同步
    - cron: '0 19 * * *'
  workflow_dispatch:
    # 手动触发同步

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出当前仓库
    - name: Checkout this repository
      uses: actions/checkout@v4

    # Step 2: 克隆目标仓库
    - name: Clone target repository
      run: |
        git clone --depth 1 https://github.com/Ftindy/IPTV-URL.git target-repo
    
    # Step 3: 复制需要同步的文件
    - name: Copy files
      run: |
        cp -R target-repo/* tvsrc
        rm -rf target-repo
    
    # Step 4: 提交和推送更改
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Sync files from target repository" 
        git push
      env:
        # 提交需要 GitHub Token 来验证推送操作
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
